// THE CAPABILITY REGISTRY (RFC 0001, phase 0)
//
// Every progressive-enhancement branch in the system is a closed `@supports`
// pair (ADR-0009, css-doctrine §5): one positive block, one negated block,
// mutually exclusive, neither aware of the other. The condition that
// discriminates between them is written here, once, and nowhere else.
//
// Today the table is read by one consumer — the capability gate
// (apps/docs/tests/capability-gate.test.ts), which requires every `@supports`
// in the codebase to match one of these conditions verbatim. The later phases
// of the RFC read the same table: the probe build (mode `probe`, the
// kitchensink side-by-side) and the force build (mode `force`, ADR-0009's
// deletion-readiness check) derive their discriminants from these keys.
//
// THE EXACT-MATCH RULE
//
// `css` is the condition exactly as it appears after `@supports ` in the
// positive branch — no outer parentheses added, no rewording. The two legal
// param strings for a key are derived, never re-typed:
//
//   positive(key)  ->  `${css}`
//   negative(key)  ->  `not ${css}`      when css is already ONE parenthesised
//                                        group, e.g. `(container-type: inline-size)`
//                  ->  `not (${css})`    otherwise, e.g. a top-level `and` chain
//
// The `not` operator requires its operand to be a single <supports-in-parens>,
// which is why the `and` chain gains one wrapping pair and a lone group does
// not. Matching is exact modulo whitespace: the gate collapses runs of
// whitespace to one space before comparing, nothing more. A condition that
// differs in any other way from the table is unregistered and the gate fails.
//
// Adding a capability: add one entry. Removing one (deletion day, ADR-0009):
// delete the entry after the fallback branches are gone — the gate then names
// any pair that still references it.

export const capabilities = {
  /** text-box-trim / text-box-edge — native cap-to-baseline trim (Heading, Text, TextBlock). */
  textTrim: { css: "(text-box-trim: trim-both) and (text-box-edge: cap alphabetic)" },
  /** Container queries (Teaser, CoverComposition). */
  cq: { css: "(container-type: inline-size)" },
  /** The :has() relational selector (docs Tables). */
  has: { css: "(selector(:has(*)))" },
  /** oklch color literals — the RAW palette's one modern dependency (generated by the token factory). */
  oklch: { css: "(color: oklch(1 0 0))" },
};

/** Collapse runs of whitespace to one space and trim — the only normalisation the gate applies. */
export const normalizeCondition = (params) => params.replace(/\s+/g, " ").trim();

/** True when `css` is exactly one balanced parenthesised group: `(…)` with the first `(` closing at the end. */
function isSingleGroup(css) {
  if (!css.startsWith("(") || !css.endsWith(")")) return false;
  let depth = 0;
  for (let i = 0; i < css.length; i++) {
    if (css[i] === "(") depth++;
    else if (css[i] === ")") depth--;
    if (depth === 0) return i === css.length - 1;
  }
  return false;
}

function entry(key) {
  const cap = capabilities[key];
  if (!cap) throw new Error(`unknown capability "${key}"`);
  return cap;
}

/** The `@supports` param string of the positive branch for `key`. */
export function positive(key) {
  return entry(key).css;
}

/** The `@supports` param string of the negated branch for `key`. */
export function negative(key) {
  const { css } = entry(key);
  return isSingleGroup(css) ? `not ${css}` : `not (${css})`;
}

/**
 * Map an `@supports` param string to its registry key and polarity,
 * or null when the condition is not registered (in either polarity).
 * @returns {{ key: string, polarity: "on" | "off" } | null}
 */
export function parseCondition(params) {
  const wanted = normalizeCondition(params);
  for (const key of Object.keys(capabilities)) {
    if (wanted === normalizeCondition(positive(key))) return { key, polarity: "on" };
    if (wanted === normalizeCondition(negative(key))) return { key, polarity: "off" };
  }
  return null;
}
